### ISSUE TITLE
Wireless NIC AP and bridged

### ISSUE THREAD

**Issue by dfarrell07** [IEEERobotics/bot#75]
We're planning on using two wireless NICs, one to create an access point generated from the bot and one to connect to the NCSU network. We will bridge the two, to allow routing to the Internet from the bone and devices connected to the bone's network.

@jschornick has configured a bone to use his custom wireless drivers, and using that setup has managed to get most of this functionally working. Once we get a replacement USB hub, we'll want to install this setup on the bot.

**Comment by AhmedSamara** [comment]
Just for posterity's sake, what exactly was the point of the dual-NIC setup?

Because if you setup just one NIC to connect to wifi, you can still SSH into the beaglebone using the hostname and have wifi on your own system.

**Comment by jschornick** [comment]
The two interface setup was primarily addressing reliability and flexibility.  

Regarding the former, the NCSU network wouldn't consistently "play nice" when it came to getting both the bot and everyone's laptop to communicate with each other.  Since we don't have direct access to the school's network hardware, it was difficult to troubleshoot and/or fix when things weren't working right.  Thus by having our own IEEEbot network, we could make things much more transparent and reliable.

One the flexibility side of things, the NCSU network could work great... when you're at NCSU.  But what about when you're not?  If that's your sole way of accessing the bot, what are you going to do when there isn't a school/corporate wifi infrastructure to hop onto?  What if it requires some authentication scheme that you can't get working on the bot?  It's much easier to have the Internet-side NIC be optional.  When it's there, great.  You get internet access on the bot and for everyone on the IEEEbot network.  When it's not, well, at least you can still connect to the bot to get things moving.  

Of course, there are probably other options I haven't thought of... but that particular dual-NIC setup seemed a good compromise between complexity and addressing all of our needs.  Happy hacking!
